name: Build

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build-debian-package:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Linux Setup
        if: runner.os == 'Linux'
        run: |
          sudo apt update

          sudo apt install --no-install-recommends -y \
            cmake \
            libasound2-dev \
            libcurl4-openssl-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev

      # - name: Windows Setup
      #   if: runner.os == 'Windows'
      #   run: |
      #     #

      # - name: Mac Setup
      #   if: runner.os == 'macOS'
      #   run: |
      #     #

      - name: Build
        run: |
          cmake .
          make -j4

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            ./*_artefacts/*
            !./*_artefacts/JuceLibraryCode
            !./*_artefacts/lib*_SharedCode.a
