name: Build

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Linux Setup
        if: runner.os == 'Linux'
        run: |
          sudo apt update

          # CACHE THESE PACKAGES

          sudo apt install --no-install-recommends -y \
            cmake \
            libasound2-dev \
            libcurl4-openssl-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev

      - run: cmake .

      - name: Add msbuild to PATH
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.1

      # TODO: infer project name from CMakeLists.txt?
      - run: msbuild AUDIO_PLUGIN_EXAMPLE.sln
        if: runner.os == 'Windows'

      - run: make -j4
        if: runner.os != 'Windows'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            ./*_artefacts/*
            !./*_artefacts/JuceLibraryCode
            !./*_artefacts/lib*_SharedCode.a
