name: Build

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build-debian-package:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential
          cmake .
          make -j4

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./AudioPluginExample_artefacts/*
