name: Build

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build-debian-package:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt update

          sudo apt install --no-install-recommends -y \
            cmake \
            libasound2-dev \
            libcurl4-openssl-dev \
            libwebkit2gtk-4.0-dev \
            libgtk-3-dev

          cmake .
          make -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./*_artefacts/*
